name: Cron Job

on:
  schedule:
    - cron: '0 0 * * *' # runs every day at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Scrape HTML and download latest installer
      run: |
        URL=$(curl -L https://support.freedomscientific.com/Downloads/JAWS | grep -o 'https://jaws20.*exe')
        curl -LJO $URL

    - name: Compare with repository file
      run: |
        cmp J20*.exe ./Installer.exe
        EXIT_CODE=$?
        if [ $EXIT_CODE == 0 ]; then
          rm J20*.exe
          echo "Installer file is already up-to-date."
          exit 0
        fi

    - name: Move to root directory
      if: ${{ success() != true }}
      run: mv J20*.exe Installer.exe

    - name: Commit changes
      if: ${{ success() != true }}
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'Update installer to latest version'
        push: true
